-- ++
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(1,0,0,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(2,1,0,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(3,2,0,2);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(4,0,1,2);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(5,1,1,3);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(6,2,1,3);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(7,0,2,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(8,1,2,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(9,2,2,2);

-- +-
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(10,0,-1,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(11,1,-1,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(12,2,-1,2);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(13,0,-2,2);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(14,1,-2,3);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(15,2,-2,3);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(16,0,-3,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(17,1,-3,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(18,2,-3,2);

-- --
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(19,-1,-1,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(20,-2,-1,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(21,-3,-1,2);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(22,-1,-2,2);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(23,-2,-2,3);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(24,-3,-2,3);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(25,-1,-3,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(26,-2,-3,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(27,-3,-3,2);

-- -+
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(28,-1,0,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(29,-2,0,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(30,-3,0,2);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(31,-1,1,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(32,-2,1,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(33,-3,1,2);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(34,-1,2,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(35,-2,2,1);
INSERT INTO MAP(ID,COORD_X,COORD_Y,TEST_TYPE) VALUES(36,-3,2,2);